/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMyLeadsRouteImport } from './routes/_authed/my-leads'
import { Route as AuthedMessagesRouteImport } from './routes/_authed/messages'
import { Route as AuthedFindLeadsRouteImport } from './routes/_authed/find-leads'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyLeadsRoute = AuthedMyLeadsRouteImport.update({
  id: '/my-leads',
  path: '/my-leads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFindLeadsRoute = AuthedFindLeadsRouteImport.update({
  id: '/find-leads',
  path: '/find-leads',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/find-leads': typeof AuthedFindLeadsRoute
  '/messages': typeof AuthedMessagesRoute
  '/my-leads': typeof AuthedMyLeadsRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/find-leads': typeof AuthedFindLeadsRoute
  '/messages': typeof AuthedMessagesRoute
  '/my-leads': typeof AuthedMyLeadsRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/find-leads': typeof AuthedFindLeadsRoute
  '/_authed/messages': typeof AuthedMessagesRoute
  '/_authed/my-leads': typeof AuthedMyLeadsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/find-leads'
    | '/messages'
    | '/my-leads'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/find-leads'
    | '/messages'
    | '/my-leads'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/find-leads'
    | '/_authed/messages'
    | '/_authed/my-leads'
    | '/_authed/settings'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-leads': {
      id: '/_authed/my-leads'
      path: '/my-leads'
      fullPath: '/my-leads'
      preLoaderRoute: typeof AuthedMyLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/find-leads': {
      id: '/_authed/find-leads'
      path: '/find-leads'
      fullPath: '/find-leads'
      preLoaderRoute: typeof AuthedFindLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedFindLeadsRoute: typeof AuthedFindLeadsRoute
  AuthedMessagesRoute: typeof AuthedMessagesRoute
  AuthedMyLeadsRoute: typeof AuthedMyLeadsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFindLeadsRoute: AuthedFindLeadsRoute,
  AuthedMessagesRoute: AuthedMessagesRoute,
  AuthedMyLeadsRoute: AuthedMyLeadsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
